# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Encoding

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Dynamic(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Dynamic()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDynamic(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Dynamic
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Dynamic
    def Name(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Dynamic
    def NameAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # Dynamic
    def NameLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Dynamic
    def NameIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Start(builder): builder.StartObject(1)
def DynamicStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def DynamicAddName(builder, name):
    """This method is deprecated. Please switch to AddName."""
    return AddName(builder, name)
def StartNameVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def DynamicStartNameVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartNameVector(builder, numElems)
def End(builder): return builder.EndObject()
def DynamicEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)